### ISSUE TITLE
Open in private Safari window

### ISSUE THREAD

**Issue by Coliinnn** [rodrigobdz/alfred-chrome-incognito-workflow#3]
Hi, thank you for this alfred workflow. Is there any way the workflow can be made to open the current link in a private safari tab instead of Chrome's incognito?

EDIT: The following Apple Script works as intended; it takes the current URL, opens a new private window, and inserts the URL there.

```
tell application "Safari"

	activate
	set theURL to the URL of the current tab of window 1
	tell application "System Events"
		tell process "Safari"
			keystroke "N" using {shift down, command down}
		end tell -- end tell process Safari
	end tell -- end tell application System Events
	delay 0.3
	set URL of current tab of front window to theURL
end tell -- end tell application Safari
```

**Comment by rodrigobdz** [comment]
Thanks @Coliinnn, I'm glad you're using it. It is possible but it would require rewriting the workflow entirely.

A simple AppleScript example on how to open a private window in Safari is described here: https://discussions.apple.com/thread/7312435?answerId=29226377022#29226377022
